package harness

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestClaudeAdapter_Name(t *testing.T) {
	a := NewClaudeAdapter("/tmp/test")
	if a.Name() != "claude" {
		t.Errorf("expected %q, got %q", "claude", a.Name())
	}
}

func TestClaudeAdapter_DetectHarness(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)
	t.Setenv("PATH", t.TempDir())

	a := NewClaudeAdapter(t.TempDir())
	if a.DetectHarness() {
		t.Error("expected false when global Claude config does not exist")
	}

	os.MkdirAll(filepath.Join(home, ".claude"), 0755)
	if !a.DetectHarness() {
		t.Error("expected true when global .claude/ exists")
	}
}

func TestClaudeAdapter_GenerateContextFile(t *testing.T) {
	dir := t.TempDir()
	a := NewClaudeAdapter(dir)

	config := Config{
		Version:  "1",
		Delivery: "context-file",
		User: UserConfig{
			Language:          "en",
			Autonomy:          "balanced",
			CommunicationMode: "concise",
		},
	}

	constraints := []Constraint{
		{ID: "anti-hallucination", Summary: "When unsure, say you don't know."},
	}

	skills := []Skill{
		{ID: "session-wrap-up", Summary: "End-of-session knowledge propagation."},
	}

	identity := &Identity{
		What: "MOM — a living knowledge infrastructure.",
	}

	if err := a.GenerateContextFile(config, constraints, skills, identity); err != nil {
		t.Fatalf("GenerateContextFile failed: %v", err)
	}

	content, err := os.ReadFile(filepath.Join(dir, ".claude", "CLAUDE.md"))
	if err != nil {
		t.Fatalf("reading CLAUDE.md: %v", err)
	}

	s := string(content)
	checks := []string{
		"Generated by MOM",
		"MOM — Memory Oriented Machine",
		"living knowledge infrastructure",
		"## Constraints",
		"anti-hallucination",
		"When unsure, say you don't know.",
		"## Skills",
		"session-wrap-up",
		"End-of-session knowledge propagation.",
		"must be written in English",
		"## Communication mode: Concise",
		"Every word earns its place",
		"Balanced",
		"Propose before",
		"## Voice",
		"## Memory",
		"## During work",
	}
	for _, check := range checks {
		if !strings.Contains(s, check) {
			t.Errorf("CLAUDE.md missing %q", check)
		}
	}
}

// TestClaudeAdapter_GenerateContextFile_NoProfile verifies that retired profile
// references (orchestrator, specialist, delegation) do NOT appear in generated output.
func TestClaudeAdapter_GenerateContextFile_NoProfile(t *testing.T) {
	dir := t.TempDir()
	a := NewClaudeAdapter(dir)

	config := Config{
		Version: "1",
		User:    UserConfig{Language: "en", Autonomy: "balanced", CommunicationMode: "concise"},
	}

	if err := a.GenerateContextFile(config, nil, nil, nil); err != nil {
		t.Fatalf("GenerateContextFile failed: %v", err)
	}

	content, err := os.ReadFile(filepath.Join(dir, ".claude", "CLAUDE.md"))
	if err != nil {
		t.Fatalf("reading CLAUDE.md: %v", err)
	}

	s := string(content)
	// These phrases indicate the retired orchestration model — they must not appear.
	forbidden := []string{"specialist", "delegation", "task-intake", "Active Profile",
		"orchestrates, never executes", "mom orchestrates", "task pipeline"}
	for _, bad := range forbidden {
		if strings.Contains(strings.ToLower(s), strings.ToLower(bad)) {
			t.Errorf("CLAUDE.md must not contain %q", bad)
		}
	}
}

func TestClaudeAdapter_GenerateContextFile_NoIdentity(t *testing.T) {
	dir := t.TempDir()
	a := NewClaudeAdapter(dir)

	config := Config{
		Version:  "1",
		Delivery: "context-file",
		User: UserConfig{
			Language: "en",
			Autonomy: "balanced",
		},
	}

	if err := a.GenerateContextFile(config, nil, nil, nil); err != nil {
		t.Fatalf("GenerateContextFile failed: %v", err)
	}

	content, err := os.ReadFile(filepath.Join(dir, ".claude", "CLAUDE.md"))
	if err != nil {
		t.Fatalf("reading CLAUDE.md: %v", err)
	}

	s := string(content)
	if !strings.Contains(s, "She remembers, so you don't have to") {
		t.Error("CLAUDE.md missing fallback identity text")
	}
}

func TestClaudeAdapter_GenerateContextFile_CommunicationModes(t *testing.T) {
	modes := []struct {
		mode string
		want string
	}{
		{"concise", "## Communication mode: Concise"},
		{"efficient", "## Communication mode: Efficient"},
	}

	for _, tc := range modes {
		t.Run(tc.mode, func(t *testing.T) {
			dir := t.TempDir()
			a := NewClaudeAdapter(dir)
			cfg := Config{
				Version:  "1",
				Delivery: "context-file",
				User:     UserConfig{Language: "en", Autonomy: "balanced", CommunicationMode: tc.mode},
			}
			if err := a.GenerateContextFile(cfg, nil, nil, nil); err != nil {
				t.Fatalf("GenerateContextFile failed: %v", err)
			}
			content, _ := os.ReadFile(filepath.Join(dir, ".claude", "CLAUDE.md"))
			if !strings.Contains(string(content), tc.want) {
				t.Errorf("CLAUDE.md missing %q for mode %q", tc.want, tc.mode)
			}
		})
	}

	// "default" mode returns empty instructions — no communication header in output.
	t.Run("default", func(t *testing.T) {
		dir := t.TempDir()
		a := NewClaudeAdapter(dir)
		cfg := Config{
			Version:  "1",
			Delivery: "context-file",
			User:     UserConfig{Language: "en", Autonomy: "balanced", CommunicationMode: "default"},
		}
		if err := a.GenerateContextFile(cfg, nil, nil, nil); err != nil {
			t.Fatalf("GenerateContextFile failed: %v", err)
		}
		content, _ := os.ReadFile(filepath.Join(dir, ".claude", "CLAUDE.md"))
		if strings.Contains(string(content), "## Communication mode") {
			t.Error("CLAUDE.md should not contain communication mode header for default mode")
		}
	})
}

func TestClaudeAdapter_RegisterHooks(t *testing.T) {
	dir := t.TempDir()
	a := NewClaudeAdapter(dir)

	if err := a.RegisterHooks(); err != nil {
		t.Fatalf("RegisterHooks failed: %v", err)
	}

	content, err := os.ReadFile(filepath.Join(dir, ".claude", "settings.json"))
	if err != nil {
		t.Fatalf("reading settings.json: %v", err)
	}

	var settings map[string]any
	if err := json.Unmarshal(content, &settings); err != nil {
		t.Fatalf("parsing settings.json: %v", err)
	}

	hooksMap, ok := settings["hooks"].(map[string]any)
	if !ok {
		t.Fatal("hooks should be a map")
	}

	stop, ok := hooksMap["Stop"].([]any)
	if !ok {
		t.Fatal("hooks.Stop should be an array")
	}
	if len(stop) != 1 {
		t.Fatalf("expected 1 Stop matcher group (sweep only), got %d", len(stop))
	}

	group0 := stop[0].(map[string]any)
	innerHooks0 := group0["hooks"].([]any)
	hookEntry0 := innerHooks0[0].(map[string]any)
	if hookEntry0["command"] != "mom watch --sweep" {
		t.Errorf("expected command 'mom watch --sweep', got %v", hookEntry0["command"])
	}

	// SessionEnd has a fallback sweep to catch the last response.
	sessionEnd, ok := hooksMap["SessionEnd"].([]any)
	if !ok {
		t.Fatal("hooks.SessionEnd should be an array")
	}
	if len(sessionEnd) != 1 {
		t.Fatalf("expected 1 SessionEnd matcher group (sweep), got %d", len(sessionEnd))
	}
	seGroup := sessionEnd[0].(map[string]any)
	seHooks := seGroup["hooks"].([]any)
	seEntry := seHooks[0].(map[string]any)
	if seEntry["command"] != "mom watch --sweep" {
		t.Errorf("expected SessionEnd command 'mom watch --sweep', got %v", seEntry["command"])
	}
}

func TestClaudeAdapter_RegisterMCP_Fresh(t *testing.T) {
	dir := t.TempDir()
	a := NewClaudeAdapter(dir)

	if err := a.RegisterMCP(); err != nil {
		t.Fatalf("RegisterMCP failed: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(dir, ".mcp.json"))
	if err != nil {
		t.Fatalf("reading .mcp.json: %v", err)
	}
	var root map[string]any
	if err := json.Unmarshal(data, &root); err != nil {
		t.Fatalf("parsing .mcp.json: %v", err)
	}
	servers, ok := root["mcpServers"].(map[string]any)
	if !ok {
		t.Fatal(".mcp.json missing mcpServers")
	}
	mom, ok := servers["mom"].(map[string]any)
	if !ok {
		t.Fatal(".mcp.json missing mom server entry")
	}
	cmd, _ := mom["command"].(string)
	if cmd == "" {
		t.Error(".mcp.json mom command must not be empty")
	}
	s := string(data)
	if !strings.Contains(s, `"serve"`) {
		t.Error(".mcp.json missing serve arg")
	}
}

func TestClaudeAdapter_RegisterMCP_PreservesExisting(t *testing.T) {
	dir := t.TempDir()
	a := NewClaudeAdapter(dir)

	// Write an existing .mcp.json with another server.
	existing := `{"mcpServers": {"other": {"command": "other-tool", "args": ["run"]}}}` + "\n"
	os.WriteFile(filepath.Join(dir, ".mcp.json"), []byte(existing), 0644)

	if err := a.RegisterMCP(); err != nil {
		t.Fatalf("RegisterMCP failed: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(dir, ".mcp.json"))
	if err != nil {
		t.Fatalf("reading .mcp.json: %v", err)
	}
	s := string(data)
	if !strings.Contains(s, `"other"`) {
		t.Error(".mcp.json lost existing server entry")
	}
	if !strings.Contains(s, `"mom"`) {
		t.Error(".mcp.json missing mom server entry")
	}
}

func TestClaudeAdapter_Watermark(t *testing.T) {
	a := NewClaudeAdapter("/tmp/test")
	wm := a.Watermark()
	if !strings.Contains(wm, "Generated by MOM") {
		t.Errorf("expected watermark to contain 'Generated by MOM', got %q", wm)
	}
}

func TestWatermarkPresent(t *testing.T) {
	dir := t.TempDir()
	a := NewClaudeAdapter(dir)

	config := Config{Version: "1", User: UserConfig{Language: "en", Autonomy: "balanced"}}

	if err := a.GenerateContextFile(config, nil, nil, nil); err != nil {
		t.Fatalf("GenerateContextFile failed: %v", err)
	}

	content, err := os.ReadFile(filepath.Join(dir, ".claude", "CLAUDE.md"))
	if err != nil {
		t.Fatal(err)
	}

	if !strings.HasPrefix(string(content), "<!-- Generated by MOM") {
		t.Error("generated file should start with watermark")
	}
}

func TestBackupCreatedForUserFile(t *testing.T) {
	dir := t.TempDir()
	userFile := filepath.Join(dir, "CLAUDE.md")
	os.WriteFile(userFile, []byte("# My custom rules"), 0644)

	backed, err := BackupIfNeeded(userFile)
	if err != nil {
		t.Fatalf("BackupIfNeeded failed: %v", err)
	}
	if !backed {
		t.Error("expected backup to be created for user file")
	}

	bkpContent, err := os.ReadFile(userFile + ".bkp")
	if err != nil {
		t.Fatal("backup file not created")
	}
	if string(bkpContent) != "# My custom rules" {
		t.Error("backup content doesn't match original")
	}
}

func TestNoBackupForLeoFile(t *testing.T) {
	dir := t.TempDir()
	leoFile := filepath.Join(dir, "CLAUDE.md")
	os.WriteFile(leoFile, []byte("<!-- Generated by MOM — do not edit manually -->\n# MOM"), 0644)

	backed, err := BackupIfNeeded(leoFile)
	if err != nil {
		t.Fatalf("BackupIfNeeded failed: %v", err)
	}
	if backed {
		t.Error("should not backup MOM-generated file")
	}
}

func TestBackupNonexistentFile(t *testing.T) {
	backed, err := BackupIfNeeded("/nonexistent/path")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if backed {
		t.Error("should not backup nonexistent file")
	}
}
