package harness

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestCodexAdapter_Name(t *testing.T) {
	a := NewCodexAdapter("/tmp/test")
	if a.Name() != "codex" {
		t.Errorf("expected %q, got %q", "codex", a.Name())
	}
}

func TestCodexAdapter_DefaultTranscriptDir(t *testing.T) {
	t.Run("uses CODEX_HOME when set", func(t *testing.T) {
		t.Setenv("CODEX_HOME", "/custom/codex")
		a := NewCodexAdapter("/tmp")
		got := a.DefaultTranscriptDir()
		want := "/custom/codex/sessions"
		if got != want {
			t.Errorf("DefaultTranscriptDir = %q, want %q", got, want)
		}
	})
	t.Run("falls back to ~/.codex/sessions when CODEX_HOME unset", func(t *testing.T) {
		t.Setenv("CODEX_HOME", "")
		a := NewCodexAdapter("/tmp")
		got := a.DefaultTranscriptDir()
		if got != "~/.codex/sessions" {
			t.Errorf("DefaultTranscriptDir = %q, want ~/.codex/sessions", got)
		}
	})
}

func TestCodexAdapter_DetectHarness(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)
	t.Setenv("CODEX_HOME", "")
	t.Setenv("PATH", t.TempDir())
	a := NewCodexAdapter(t.TempDir())

	if a.DetectHarness() {
		t.Error("expected false when global Codex config does not exist")
	}

	os.MkdirAll(filepath.Join(home, ".codex"), 0755)
	if !a.DetectHarness() {
		t.Error("expected true when global .codex/ exists")
	}
}

func TestCodexAdapter_GenerateContextFile(t *testing.T) {
	dir := t.TempDir()
	a := NewCodexAdapter(dir)

	config := Config{
		Version:  "1",
		Delivery: "context-file",
		User:     UserConfig{Language: "en", Autonomy: "balanced", CommunicationMode: "concise"},
	}
	constraints := []Constraint{{ID: "anti-hallucination", Summary: "Don't guess."}}
	skills := []Skill{{ID: "session-wrap-up", Summary: "End-of-session."}}
	identity := &Identity{What: "MOM — a living knowledge infrastructure."}

	if err := a.GenerateContextFile(config, constraints, skills, identity); err != nil {
		t.Fatalf("GenerateContextFile failed: %v", err)
	}

	content, err := os.ReadFile(filepath.Join(dir, "AGENTS.md"))
	if err != nil {
		t.Fatalf("reading AGENTS.md: %v", err)
	}

	s := string(content)
	checks := []string{
		"Generated by MOM",
		"MOM — Memory Oriented Machine",
		"anti-hallucination",
		"session-wrap-up",
		"## Memory",
	}
	for _, check := range checks {
		if !strings.Contains(s, check) {
			t.Errorf("AGENTS.md missing %q", check)
		}
	}
}

func TestCodexAdapter_GenerateContextFileWatermark(t *testing.T) {
	dir := t.TempDir()
	a := NewCodexAdapter(dir)

	config := Config{Version: "1", User: UserConfig{Language: "en", Autonomy: "balanced"}}

	if err := a.GenerateContextFile(config, nil, nil, nil); err != nil {
		t.Fatal(err)
	}

	content, _ := os.ReadFile(filepath.Join(dir, "AGENTS.md"))
	if !strings.HasPrefix(string(content), "<!-- Generated by MOM") {
		t.Error("AGENTS.md should start with watermark")
	}
}

func TestCodexAdapter_RegisterHooks(t *testing.T) {
	dir := t.TempDir()
	a := NewCodexAdapter(dir)

	if err := a.RegisterHooks(); err != nil {
		t.Fatalf("RegisterHooks failed: %v", err)
	}

	hooksPath := filepath.Join(dir, ".codex", "hooks.json")
	content, err := os.ReadFile(hooksPath)
	if err != nil {
		t.Fatalf("reading hooks.json: %v", err)
	}

	// Verify top-level "hooks" key wrapping the event map.
	var root map[string]any
	if err := json.Unmarshal(content, &root); err != nil {
		t.Fatalf("parsing hooks.json: %v", err)
	}

	hooksMap, ok := root["hooks"].(map[string]any)
	if !ok {
		t.Fatal("hooks.json should have top-level 'hooks' key wrapping events")
	}

	stop, ok := hooksMap["Stop"].([]any)
	if !ok {
		t.Fatal("hooks.Stop should be an array")
	}
	if len(stop) != 1 {
		t.Fatalf("expected 1 Stop matcher group, got %d", len(stop))
	}

	group, ok := stop[0].(map[string]any)
	if !ok {
		t.Fatal("matcher group should be a map")
	}
	innerHooks, ok := group["hooks"].([]any)
	if !ok || len(innerHooks) == 0 {
		t.Fatal("matcher group should have a hooks array")
	}
	hookEntry, ok := innerHooks[0].(map[string]any)
	if !ok {
		t.Fatal("hook entry should be a map")
	}
	if hookEntry["type"] != "command" {
		t.Errorf("expected type 'command', got %v", hookEntry["type"])
	}
	command, _ := hookEntry["command"].(string)
	if !strings.Contains(command, "watch --sweep --global") {
		t.Errorf("expected command to run global sweep, got %v", hookEntry["command"])
	}
}

func TestCodexAdapter_RegisterMCP(t *testing.T) {
	dir := t.TempDir()
	a := NewCodexAdapter(dir)

	if err := a.RegisterMCP(); err != nil {
		t.Fatalf("RegisterMCP failed: %v", err)
	}

	// Verify .mcp.json (shared with other Harnesses).
	data, err := os.ReadFile(filepath.Join(dir, ".mcp.json"))
	if err != nil {
		t.Fatalf("reading .mcp.json: %v", err)
	}
	s := string(data)
	if !strings.Contains(s, `"mom"`) {
		t.Error(".mcp.json missing mom server entry")
	}

	// Verify project-level .codex/config.toml (what Codex actually reads).
	tomlData, err := os.ReadFile(filepath.Join(dir, ".codex", "config.toml"))
	if err != nil {
		t.Fatalf("reading .codex/config.toml: %v", err)
	}
	toml := string(tomlData)
	if !strings.Contains(toml, "[mcp_servers.mom]") {
		t.Error("config.toml missing [mcp_servers.mom] section")
	}
	if !strings.Contains(toml, "command = ") {
		t.Error("config.toml missing command entry for mom")
	}
	if !strings.Contains(toml, "hooks = true") {
		t.Error("config.toml missing hooks feature flag")
	}
	if strings.Contains(toml, "codex_hooks") {
		t.Error("config.toml should not use deprecated codex_hooks feature flag")
	}
}

func TestCodexAdapter_RegisterMCP_Idempotent(t *testing.T) {
	dir := t.TempDir()
	a := NewCodexAdapter(dir)

	// Call twice — should not duplicate the section.
	a.RegisterMCP()
	a.RegisterMCP()

	data, _ := os.ReadFile(filepath.Join(dir, ".codex", "config.toml"))
	content := string(data)
	count := strings.Count(content, "[mcp_servers.mom]")
	if count != 1 {
		t.Errorf("expected 1 [mcp_servers.mom] section, got %d", count)
	}
	count = strings.Count(content, "hooks = true")
	if count != 1 {
		t.Errorf("expected 1 hooks entry, got %d", count)
	}
	if strings.Contains(content, "codex_hooks") {
		t.Error("config.toml should not use deprecated codex_hooks feature flag")
	}
}

func TestCodexAdapter_RegisterMCP_NormalizesDuplicateFeaturesBlocks(t *testing.T) {
	dir := t.TempDir()
	codexDir := filepath.Join(dir, ".codex")
	if err := os.MkdirAll(codexDir, 0o755); err != nil {
		t.Fatal(err)
	}
	existing := `[projects."/some/path"]
trust_level = "trusted"

[features]
codex_hooks = true

[hooks.state]

[features]
hooks = true
`
	if err := os.WriteFile(filepath.Join(codexDir, "config.toml"), []byte(existing), 0o644); err != nil {
		t.Fatal(err)
	}

	a := NewCodexAdapter(dir)
	if err := a.RegisterMCP(); err != nil {
		t.Fatalf("RegisterMCP failed: %v", err)
	}

	data, _ := os.ReadFile(filepath.Join(codexDir, "config.toml"))
	content := string(data)
	if count := strings.Count(content, "[features]"); count != 1 {
		t.Fatalf("expected one [features] block, got %d:\n%s", count, content)
	}
	if count := strings.Count(content, "hooks = true"); count != 1 {
		t.Fatalf("expected one hooks flag, got %d:\n%s", count, content)
	}
	if strings.Contains(content, "codex_hooks") {
		t.Fatalf("deprecated codex_hooks should be removed:\n%s", content)
	}
	if !strings.Contains(content, "[hooks.state]") {
		t.Fatalf("unrelated TOML sections should be preserved:\n%s", content)
	}
}

func TestCodexAdapter_RegisterMCP_PreservesExisting(t *testing.T) {
	dir := t.TempDir()
	os.MkdirAll(filepath.Join(dir, ".codex"), 0755)

	// Pre-existing config with trust level.
	existing := "[projects.\"/some/path\"]\ntrust_level = \"trusted\"\n"
	os.WriteFile(filepath.Join(dir, ".codex", "config.toml"), []byte(existing), 0644)

	a := NewCodexAdapter(dir)
	if err := a.RegisterMCP(); err != nil {
		t.Fatalf("RegisterMCP failed: %v", err)
	}

	data, _ := os.ReadFile(filepath.Join(dir, ".codex", "config.toml"))
	content := string(data)

	if !strings.Contains(content, "trust_level") {
		t.Error("RegisterMCP should preserve existing config content")
	}
	if !strings.Contains(content, "[mcp_servers.mom]") {
		t.Error("RegisterMCP should add MCP section")
	}
}

func TestCodexAdapter_GeneratedFiles(t *testing.T) {
	a := NewCodexAdapter("/tmp/test")
	files := a.GeneratedFiles()
	expected := []string{"AGENTS.md", filepath.Join(".codex", "hooks.json"), filepath.Join(".codex", "config.toml"), ".mcp.json"}
	if len(files) != len(expected) {
		t.Fatalf("expected %d files, got %d: %v", len(expected), len(files), files)
	}
	for i, f := range files {
		if f != expected[i] {
			t.Errorf("expected files[%d] = %q, got %q", i, expected[i], f)
		}
	}
}

func TestCodexAdapter_GeneratedDirs(t *testing.T) {
	a := NewCodexAdapter("/tmp/test")
	dirs := a.GeneratedDirs()
	if len(dirs) != 1 || dirs[0] != ".codex" {
		t.Errorf("expected [.codex], got %v", dirs)
	}
}

func TestCodexAdapter_NoIdentity(t *testing.T) {
	dir := t.TempDir()
	a := NewCodexAdapter(dir)

	config := Config{Version: "1", Delivery: "context-file", User: UserConfig{Language: "en", Autonomy: "balanced"}}

	if err := a.GenerateContextFile(config, nil, nil, nil); err != nil {
		t.Fatal(err)
	}

	content, _ := os.ReadFile(filepath.Join(dir, "AGENTS.md"))
	if !strings.Contains(string(content), "You are MOM") {
		t.Error("should have fallback identity")
	}
}

// TestCodexAdapter_RegisterGlobalHooks_WritesToHomeCodexDir locks the
// global-install contract: mom init --harnesses codex must drop
// hooks.json at ~/.codex/ so Codex Desktop fires `mom watch --sweep --global`
// after each Cascade response. Without this, only project-local
// inits get the hook wired.
func TestCodexAdapter_RegisterGlobalHooks_WritesToHomeCodexDir(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)
	t.Setenv("CODEX_HOME", "")
	a := NewCodexAdapter("/tmp/unused-project-root")

	if err := a.RegisterGlobalHooks(); err != nil {
		t.Fatalf("RegisterGlobalHooks: %v", err)
	}

	hooksPath := filepath.Join(home, ".codex", "hooks.json")
	data, err := os.ReadFile(hooksPath)
	if err != nil {
		t.Fatalf("reading global hooks.json: %v", err)
	}
	var root map[string]any
	if err := json.Unmarshal(data, &root); err != nil {
		t.Fatalf("parse hooks.json: %v", err)
	}
	hooks, ok := root["hooks"].(map[string]any)
	if !ok {
		t.Fatal("missing top-level 'hooks' key")
	}
	stop, ok := hooks["Stop"].([]any)
	if !ok || len(stop) == 0 {
		t.Fatal("missing Stop event")
	}
	group := stop[0].(map[string]any)
	inner := group["hooks"].([]any)
	entry := inner[0].(map[string]any)
	command, _ := entry["command"].(string)
	if !strings.Contains(command, "watch --sweep --global") {
		t.Errorf("Stop hook command = %v, want global sweep", entry["command"])
	}
}

// CODEX_HOME override puts the hooks.json under the override path.
func TestCodexAdapter_RegisterGlobalHooks_HonorsCodexHome(t *testing.T) {
	codexHome := t.TempDir()
	t.Setenv("HOME", t.TempDir())
	t.Setenv("CODEX_HOME", codexHome)
	a := NewCodexAdapter("/tmp/unused")

	if err := a.RegisterGlobalHooks(); err != nil {
		t.Fatalf("RegisterGlobalHooks: %v", err)
	}
	if _, err := os.Stat(filepath.Join(codexHome, "hooks.json")); err != nil {
		t.Errorf("expected hooks.json under CODEX_HOME, got: %v", err)
	}
}

func TestCodexAdapter_RegisterMCP_RefreshesStaleCommand(t *testing.T) {
	dir := t.TempDir()
	codexDir := filepath.Join(dir, ".codex")
	if err := os.MkdirAll(codexDir, 0o755); err != nil {
		t.Fatal(err)
	}
	existing := `[mcp_servers.mom]
command = "/tmp/mom-dev"
args = ["serve", "mcp"]

[mcp_servers.mom.env]
MOM_PROJECT_DIR = "/private/tmp/stale"

[features]
hooks = true
`
	if err := os.WriteFile(filepath.Join(codexDir, "config.toml"), []byte(existing), 0o644); err != nil {
		t.Fatal(err)
	}

	a := NewCodexAdapter(dir)
	if err := a.RegisterMCP(); err != nil {
		t.Fatalf("RegisterMCP failed: %v", err)
	}

	data, _ := os.ReadFile(filepath.Join(codexDir, "config.toml"))
	content := string(data)
	if strings.Contains(content, "/tmp/mom-dev") {
		t.Fatalf("stale command path should be replaced:\n%s", content)
	}
	if !strings.Contains(content, `command = "mom"`) {
		t.Fatalf("canonical command should be \"mom\":\n%s", content)
	}
	if strings.Contains(content, "MOM_PROJECT_DIR") {
		t.Fatalf("stale [mcp_servers.mom.env] should be dropped:\n%s", content)
	}
	if count := strings.Count(content, "[mcp_servers.mom]"); count != 1 {
		t.Fatalf("expected exactly one [mcp_servers.mom] block, got %d:\n%s", count, content)
	}
}
