package harness

import (
	_ "embed"
	"fmt"
	"os"
	"path/filepath"

	"gopkg.in/yaml.v3"
)

//go:embed capabilities/pi.yaml
var piCapabilitiesYAML []byte

// piMomToolsExtension is the source of the .pi/extensions/mom-tools.ts file
// that exposes MOM's MCP tools as native pi tools. Embedded so `mom init`
// can lay it down without depending on a network or external package.
//
//go:embed pi_assets/mom-tools.ts
var piMomToolsExtension []byte

// PiAdapter implements the Adapter interface for pi
// (https://github.com/mariozechner/pi), a TypeScript-based coding agent.
//
// Pi reads AGENTS.md at the project root for context (shared with Codex)
// and supports project-local extensions in .pi/extensions/. It has no
// native hook system; instead, "RegisterHooks" lays down a TypeScript
// extension that wires MOM's MCP tools into pi as first-class native tools.
type PiAdapter struct {
	projectRoot string
}

// NewPiAdapter creates a PiAdapter for the given project root.
func NewPiAdapter(projectRoot string) *PiAdapter {
	return &PiAdapter{projectRoot: projectRoot}
}

func (a *PiAdapter) Name() string { return "pi" }

func (a *PiAdapter) Tier() Tier { return Native }

func (a *PiAdapter) GenerateContextFile(config Config, constraints []Constraint, skills []Skill, identity *Identity) error {
	var body string
	if config.Delivery == "context-file" {
		body = BuildContextContent(config, constraints, skills, identity)
	} else {
		body = BuildMinimalContextContent()
	}
	content := a.Watermark() + "\n\n" + body

	// AGENTS.md is shared with Codex; both Harnesses produce identical content
	// from the same .mom/ inputs, so co-installation is a no-op collision.
	agentsFile := filepath.Join(a.projectRoot, "AGENTS.md")
	if err := os.WriteFile(agentsFile, []byte(content), 0644); err != nil {
		return fmt.Errorf("writing AGENTS.md: %w", err)
	}
	return nil
}

// DefaultTranscriptDir returns pi's session transcript directory.
func (a *PiAdapter) DefaultTranscriptDir() string {
	return "~/.pi/agent/sessions/"
}

// RegisterExtension lays down the MOM TypeScript extension in .pi/extensions/.
func (a *PiAdapter) RegisterExtension() error {
	extDir := filepath.Join(a.projectRoot, ".pi", "extensions")
	if err := os.MkdirAll(extDir, 0755); err != nil {
		return fmt.Errorf("creating .pi/extensions dir: %w", err)
	}

	target := filepath.Join(extDir, "mom-tools.ts")
	if err := os.WriteFile(target, piMomToolsExtension, 0644); err != nil {
		return fmt.Errorf("writing %s: %w", target, err)
	}
	return nil
}

func (a *PiAdapter) DetectHarness() bool {
	if commandExists("pi") {
		return true
	}
	if path, err := homePath(".pi", "agent"); err == nil && pathExists(path) {
		return true
	}
	return false
}

func (a *PiAdapter) GenerateGlobalContextFile(config Config, constraints []Constraint, skills []Skill, identity *Identity) error {
	path, err := homePath(".pi", "agent", "AGENTS.md")
	if err != nil {
		return err
	}
	return upsertManagedBlock(path, buildGlobalContext(a.Watermark(), config, constraints, skills, identity))
}

func (a *PiAdapter) RegisterGlobalMCP() error {
	return nil
}

func (a *PiAdapter) RegisterGlobalExtension() error {
	extDir, err := homePath(".pi", "agent", "extensions")
	if err != nil {
		return err
	}
	if err := os.MkdirAll(extDir, 0755); err != nil {
		return fmt.Errorf("creating pi global extensions dir: %w", err)
	}
	target := filepath.Join(extDir, "mom-tools.ts")
	if err := os.WriteFile(target, piMomToolsExtension, 0644); err != nil {
		return fmt.Errorf("writing %s: %w", target, err)
	}
	return nil
}

// RegisterMCP writes the MOM MCP server entry to the project-level .mcp.json,
// which is the file pi reads for MCP server config (verified empirically:
// pi's MCP gateway picks up servers from <projectRoot>/.mcp.json).
//
// MOM_PROJECT_DIR is set so the MCP server resolves the correct scope when pi
// spawns it from a different cwd (which it does — pi launches MCP children
// from its own working directory, not necessarily the project root).
func (a *PiAdapter) RegisterMCP() error {
	mcpPath := filepath.Join(a.projectRoot, ".mcp.json")
	return upsertMCPEntryWithEnv(mcpPath, a.projectRoot)
}

func (a *PiAdapter) GeneratedFiles() []string {
	return []string{
		"AGENTS.md",
		filepath.Join(".pi", "extensions", "mom-tools.ts"),
		".mcp.json",
	}
}

func (a *PiAdapter) GeneratedDirs() []string {
	return []string{".pi"}
}

func (a *PiAdapter) Watermark() string {
	return "<!-- Generated by MOM — do not edit manually -->"
}

func (a *PiAdapter) Capabilities() AdapterCapability {
	var cap AdapterCapability
	if err := yaml.Unmarshal(piCapabilitiesYAML, &cap); err != nil {
		return AdapterCapability{Name: "pi", Version: "1.0"}
	}
	return cap
}

var (
	_ GlobalAdapter            = (*PiAdapter)(nil)
	_ GlobalExtensionInstaller = (*PiAdapter)(nil)
	_ ExtensionInstaller       = (*PiAdapter)(nil)
	_ TranscriptSource         = (*PiAdapter)(nil)
)
