package harness

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestPiAdapter_Name(t *testing.T) {
	if got := NewPiAdapter("/tmp/x").Name(); got != "pi" {
		t.Errorf("Name(): got %q, want pi", got)
	}
}

func TestPiAdapter_GenerateContextFile(t *testing.T) {
	dir := t.TempDir()
	a := NewPiAdapter(dir)

	cfg := Config{
		Version:  "1",
		Delivery: "context-file",
		User: UserConfig{
			Language:          "en",
			Autonomy:          "balanced",
			CommunicationMode: "concise",
		},
	}
	constraints := []Constraint{
		{ID: "anti-hallucination", Summary: "When unsure, say you don't know."},
	}
	skills := []Skill{
		{ID: "session-wrap-up", Summary: "End-of-session knowledge propagation."},
	}
	identity := &Identity{What: "MOM — a living knowledge infrastructure."}

	if err := a.GenerateContextFile(cfg, constraints, skills, identity); err != nil {
		t.Fatalf("GenerateContextFile: %v", err)
	}

	content, err := os.ReadFile(filepath.Join(dir, "AGENTS.md"))
	if err != nil {
		t.Fatalf("reading AGENTS.md: %v", err)
	}
	s := string(content)
	if !strings.Contains(s, "Generated by MOM") {
		t.Error("AGENTS.md missing watermark")
	}
	if !strings.Contains(s, "anti-hallucination") {
		t.Error("AGENTS.md missing constraint")
	}
	if !strings.Contains(s, "session-wrap-up") {
		t.Error("AGENTS.md missing skill")
	}
}

func TestPiAdapter_GenerateContextFile_MinimalDelivery(t *testing.T) {
	dir := t.TempDir()
	a := NewPiAdapter(dir)

	cfg := Config{Version: "1", Delivery: "mcp"}
	if err := a.GenerateContextFile(cfg, nil, nil, nil); err != nil {
		t.Fatalf("GenerateContextFile: %v", err)
	}

	content, _ := os.ReadFile(filepath.Join(dir, "AGENTS.md"))
	if !strings.Contains(string(content), "Generated by MOM") {
		t.Error("AGENTS.md missing watermark in minimal mode")
	}
}

func TestPiAdapter_RegisterExtension_LaysDownExtension(t *testing.T) {
	dir := t.TempDir()
	a := NewPiAdapter(dir)

	if err := a.RegisterExtension(); err != nil {
		t.Fatalf("RegisterExtension: %v", err)
	}

	target := filepath.Join(dir, ".pi", "extensions", "mom-tools.ts")
	data, err := os.ReadFile(target)
	if err != nil {
		t.Fatalf("reading mom-tools.ts: %v", err)
	}
	if len(data) == 0 {
		t.Fatal("mom-tools.ts is empty")
	}

	// Sanity check: the embedded extension exposes a default factory that
	// registers MOM tools with pi. Match a couple of stable phrases without
	// being too brittle.
	s := string(data)
	for _, want := range []string{
		"export default",
		"pi.registerTool",
		"mom",
		"ctx.sessionManager.getSessionId()",
	} {
		if !strings.Contains(s, want) {
			t.Errorf("mom-tools.ts missing expected token %q", want)
		}
	}
}

func TestPiAdapter_RegisterExtension_Idempotent(t *testing.T) {
	dir := t.TempDir()
	a := NewPiAdapter(dir)

	if err := a.RegisterExtension(); err != nil {
		t.Fatalf("first RegisterExtension: %v", err)
	}
	if err := a.RegisterExtension(); err != nil {
		t.Fatalf("second RegisterExtension: %v", err)
	}

	// Second call should overwrite cleanly with identical content.
	target := filepath.Join(dir, ".pi", "extensions", "mom-tools.ts")
	if _, err := os.Stat(target); err != nil {
		t.Errorf("mom-tools.ts missing after second call: %v", err)
	}
}

func TestPiAdapter_RegisterMCP_FreshFile(t *testing.T) {
	dir := t.TempDir()
	a := NewPiAdapter(dir)

	if err := a.RegisterMCP(); err != nil {
		t.Fatalf("RegisterMCP: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(dir, ".mcp.json"))
	if err != nil {
		t.Fatalf("reading .mcp.json: %v", err)
	}
	var root map[string]any
	if err := json.Unmarshal(data, &root); err != nil {
		t.Fatalf("parsing .mcp.json: %v", err)
	}
	servers, ok := root["mcpServers"].(map[string]any)
	if !ok {
		t.Fatal(".mcp.json missing mcpServers")
	}
	mom, ok := servers["mom"].(map[string]any)
	if !ok {
		t.Fatal(".mcp.json missing mom entry")
	}
	if cmd, _ := mom["command"].(string); cmd == "" {
		t.Error("mom.command must not be empty")
	}
	if env, ok := mom["env"].(map[string]any); !ok {
		t.Error("mom.env missing")
	} else if env["MOM_PROJECT_DIR"] != dir {
		t.Errorf("MOM_PROJECT_DIR: got %v, want %s", env["MOM_PROJECT_DIR"], dir)
	}
	if !strings.Contains(string(data), `"serve"`) {
		t.Error(".mcp.json missing serve arg")
	}
}

func TestPiAdapter_RegisterMCP_PreservesOtherServers(t *testing.T) {
	dir := t.TempDir()
	mcpPath := filepath.Join(dir, ".mcp.json")

	// Pre-existing .mcp.json with another server entry.
	pre := map[string]any{
		"mcpServers": map[string]any{
			"other": map[string]any{
				"command": "/usr/bin/other",
				"args":    []any{"--foo"},
			},
		},
	}
	preData, _ := json.MarshalIndent(pre, "", "  ")
	if err := os.WriteFile(mcpPath, preData, 0644); err != nil {
		t.Fatal(err)
	}

	a := NewPiAdapter(dir)
	if err := a.RegisterMCP(); err != nil {
		t.Fatalf("RegisterMCP: %v", err)
	}

	data, _ := os.ReadFile(mcpPath)
	var root map[string]any
	if err := json.Unmarshal(data, &root); err != nil {
		t.Fatalf("parsing .mcp.json: %v", err)
	}
	servers := root["mcpServers"].(map[string]any)
	if _, ok := servers["other"]; !ok {
		t.Error("other server entry was clobbered by RegisterMCP")
	}
	if _, ok := servers["mom"]; !ok {
		t.Error("mom server entry was not added")
	}
}

func TestPiAdapter_DetectHarness(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)
	t.Setenv("PATH", t.TempDir())
	a := NewPiAdapter(t.TempDir())

	if a.DetectHarness() {
		t.Error("expected false when global pi config absent")
	}

	if err := os.MkdirAll(filepath.Join(home, ".pi", "agent"), 0755); err != nil {
		t.Fatal(err)
	}
	if !a.DetectHarness() {
		t.Error("expected true when global pi config exists")
	}
}

func TestPiAdapter_DetectHarness_DoesNotMatchOnAGENTSMd(t *testing.T) {
	t.Setenv("HOME", t.TempDir())
	t.Setenv("PATH", t.TempDir())
	// Codex also writes AGENTS.md. Pi must NOT report itself as detected
	// based on AGENTS.md alone, otherwise every Codex project would
	// spuriously claim pi.
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "AGENTS.md"), []byte("..."), 0644); err != nil {
		t.Fatal(err)
	}
	if NewPiAdapter(dir).DetectHarness() {
		t.Error("AGENTS.md alone must not trigger pi detection")
	}
}

func TestPiAdapter_GeneratedFiles(t *testing.T) {
	a := NewPiAdapter("/tmp/x")
	got := a.GeneratedFiles()
	want := []string{
		"AGENTS.md",
		filepath.Join(".pi", "extensions", "mom-tools.ts"),
		".mcp.json",
	}
	if len(got) != len(want) {
		t.Fatalf("len: got %d, want %d", len(got), len(want))
	}
	for i := range want {
		if got[i] != want[i] {
			t.Errorf("file[%d]: got %q, want %q", i, got[i], want[i])
		}
	}
}

func TestPiAdapter_GeneratedDirs(t *testing.T) {
	a := NewPiAdapter("/tmp/x")
	got := a.GeneratedDirs()
	if len(got) != 1 || got[0] != ".pi" {
		t.Errorf("GeneratedDirs: got %v, want [.pi]", got)
	}
}

func TestPiAdapter_Watermark(t *testing.T) {
	a := NewPiAdapter("/tmp/x")
	if !strings.Contains(a.Watermark(), "Generated by MOM") {
		t.Errorf("watermark: %q", a.Watermark())
	}
}

// TestPiAdapter_Capabilities lives in capabilities_test.go alongside the
// other adapters' capability tests — keeping the cross-Harness contract
// (Supports vs Experimental, no overlap) in one place.
