package harness

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestWindsurfAdapter_GenerateContextFile(t *testing.T) {
	dir := t.TempDir()
	a := NewWindsurfAdapter(dir)

	config := Config{
		Version:  "1",
		Delivery: "context-file",
		User: UserConfig{
			Language:          "en",
			Autonomy:          "balanced",
			CommunicationMode: "concise",
		},
	}

	constraints := []Constraint{
		{ID: "anti-hallucination", Summary: "When unsure, say you don't know."},
	}

	skills := []Skill{
		{ID: "session-wrap-up", Summary: "End-of-session knowledge propagation."},
	}

	identity := &Identity{
		What: "MOM — a living knowledge infrastructure.",
	}

	if err := a.GenerateContextFile(config, constraints, skills, identity); err != nil {
		t.Fatalf("GenerateContextFile failed: %v", err)
	}

	content, err := os.ReadFile(filepath.Join(dir, ".windsurf", "rules", "mom.md"))
	if err != nil {
		t.Fatalf("reading mom.md: %v", err)
	}

	s := string(content)
	if !strings.Contains(s, "Generated by MOM") {
		t.Error("mom.md missing watermark")
	}
	if !strings.Contains(s, "anti-hallucination") {
		t.Error("mom.md missing constraint")
	}
	if !strings.Contains(s, "session-wrap-up") {
		t.Error("mom.md missing skill")
	}
}

func TestWindsurfAdapter_FrontmatterFormat(t *testing.T) {
	dir := t.TempDir()
	a := NewWindsurfAdapter(dir)

	config := Config{
		Version:  "1",
		Delivery: "context-file",
		User:     UserConfig{Language: "en", Autonomy: "balanced", CommunicationMode: "concise"},
	}

	if err := a.GenerateContextFile(config, nil, nil, nil); err != nil {
		t.Fatalf("GenerateContextFile failed: %v", err)
	}

	content, err := os.ReadFile(filepath.Join(dir, ".windsurf", "rules", "mom.md"))
	if err != nil {
		t.Fatalf("reading mom.md: %v", err)
	}

	s := string(content)
	if !strings.HasPrefix(s, "---\ntrigger: always_on\n---") {
		t.Errorf("mom.md should start with YAML frontmatter, got: %q", s[:min(len(s), 60)])
	}
}

func TestWindsurfAdapter_RegisterHooks(t *testing.T) {
	dir := t.TempDir()
	a := NewWindsurfAdapter(dir)

	if err := a.RegisterHooks(); err != nil {
		t.Fatalf("RegisterHooks failed: %v", err)
	}

	content, err := os.ReadFile(filepath.Join(dir, ".windsurf", "hooks.json"))
	if err != nil {
		t.Fatalf("reading hooks.json: %v", err)
	}

	var root map[string]any
	if err := json.Unmarshal(content, &root); err != nil {
		t.Fatalf("parsing hooks.json: %v", err)
	}

	// Windsurf format requires top-level "hooks" key.
	hooksObj, ok := root["hooks"].(map[string]any)
	if !ok {
		t.Fatal("hooks.json missing top-level 'hooks' key")
	}

	event, ok := hooksObj["post_cascade_response_with_transcript"].([]any)
	if !ok {
		t.Fatal("hooks.json missing post_cascade_response_with_transcript event")
	}
	// Recording is done by the filesystem watcher (mom watch --runtime windsurf).
	// Only mom draft should remain — mom record is intentionally absent (#145).
	if len(event) != 1 {
		t.Fatalf("expected 1 hook entry (mom draft only), got %d", len(event))
	}

	// Verify the sole hook command is "mom draft" with working_directory.
	entry0 := event[0].(map[string]any)
	if entry0["command"] != "mom draft" {
		t.Errorf("expected command 'mom draft', got %v", entry0["command"])
	}
	if entry0["working_directory"] != dir {
		t.Errorf("expected working_directory %q, got %v", dir, entry0["working_directory"])
	}
}

func TestWindsurfAdapter_RegisterMCP(t *testing.T) {
	dir := t.TempDir()
	// Isolate HOME so the test never touches the real ~/.codeium/windsurf/mcp_config.json.
	t.Setenv("HOME", dir)
	a := NewWindsurfAdapter(dir)

	if err := a.RegisterMCP(); err != nil {
		t.Fatalf("RegisterMCP failed: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(dir, ".mcp.json"))
	if err != nil {
		t.Fatalf("reading .mcp.json: %v", err)
	}
	var root map[string]any
	if err := json.Unmarshal(data, &root); err != nil {
		t.Fatalf("parsing .mcp.json: %v", err)
	}
	servers, ok := root["mcpServers"].(map[string]any)
	if !ok {
		t.Fatal(".mcp.json missing mcpServers")
	}
	mom, ok := servers["mom"].(map[string]any)
	if !ok {
		t.Fatal(".mcp.json missing mom server entry")
	}
	cmd, _ := mom["command"].(string)
	if cmd == "" {
		t.Error(".mcp.json mom command must not be empty")
	}
	s := string(data)
	if !strings.Contains(s, `"serve"`) {
		t.Error(".mcp.json missing serve arg")
	}
}

func TestWindsurfAdapter_GeneratedFiles(t *testing.T) {
	a := NewWindsurfAdapter("/tmp/test")
	files := a.GeneratedFiles()

	expected := []string{
		filepath.Join(".windsurf", "rules", "mom.md"),
		filepath.Join(".windsurf", "hooks.json"),
		".mcp.json",
	}

	if len(files) != len(expected) {
		t.Fatalf("expected %d files, got %d", len(expected), len(files))
	}

	for i, f := range files {
		if f != expected[i] {
			t.Errorf("file[%d]: expected %q, got %q", i, expected[i], f)
		}
	}
}

func TestWindsurfAdapter_DetectHarness(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)
	t.Setenv("PATH", t.TempDir())
	a := NewWindsurfAdapter(t.TempDir())

	if a.DetectHarness() {
		t.Error("expected false when global Windsurf config does not exist")
	}

	os.MkdirAll(filepath.Join(home, ".codeium", "windsurf"), 0755)
	if !a.DetectHarness() {
		t.Error("expected true when global Windsurf config exists")
	}
}
