package cmd

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/momhq/mom/cli/internal/config"
)

// ── Helpers ──────────────────────────────────────────────────────────────────

func resetInitFlags() {
	f := initCmd.Flags()
	if h := f.Lookup("harnesses"); h != nil {
		h.Value.Set("")
		h.Changed = false
	}
	f.Set("force", "false")
	f.Set("no-interactive", "false")
}

func initProject(t *testing.T, dir string, harnesses []string) string {
	t.Helper()
	origDir, _ := os.Getwd()
	os.Chdir(dir)
	t.Cleanup(func() { os.Chdir(origDir) })

	// Reset flags BEFORE execute to avoid cross-test contamination.
	resetInitFlags()
	oldRunner := runExternalCommand
	runExternalCommand = func(string, ...string) ([]byte, error) { return []byte("ok"), nil }
	t.Cleanup(func() { runExternalCommand = oldRunner })

	buf := new(bytes.Buffer)
	rootCmd.SetOut(buf)
	rootCmd.SetErr(buf)
	rootCmd.SetArgs([]string{"init", "--harnesses", strings.Join(harnesses, ",")})
	t.Cleanup(resetInitFlags)

	if err := rootCmd.Execute(); err != nil {
		t.Fatalf("init failed: %v\noutput: %s", err, buf.String())
	}
	return buf.String()
}

func upgradeProject(t *testing.T, dir string, extraArgs ...string) string {
	t.Helper()
	origDir, _ := os.Getwd()
	os.Chdir(dir)
	t.Cleanup(func() { os.Chdir(origDir) })

	buf := new(bytes.Buffer)
	rootCmd.SetOut(buf)
	rootCmd.SetErr(buf)
	args := append([]string{"upgrade"}, extraArgs...)
	rootCmd.SetArgs(args)
	t.Cleanup(func() {
		upgradeCmd.Flags().Set("dry-run", "false")
	})

	if err := rootCmd.Execute(); err != nil {
		t.Fatalf("upgrade failed: %v\noutput: %s", err, buf.String())
	}
	return buf.String()
}

func assertFileExists(t *testing.T, path string) {
	t.Helper()
	if _, err := os.Stat(path); err != nil {
		t.Errorf("expected file to exist: %s", path)
	}
}

func assertFileNotExists(t *testing.T, path string) {
	t.Helper()
	if _, err := os.Stat(path); err == nil {
		t.Errorf("expected file NOT to exist: %s", path)
	}
}

func assertFileContains(t *testing.T, path, substr string) {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Errorf("cannot read %s: %v", path, err)
		return
	}
	if !strings.Contains(string(data), substr) {
		t.Errorf("%s does not contain %q", path, substr)
	}
}

func readJSONFile(t *testing.T, path string) map[string]any {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("cannot read %s: %v", path, err)
	}
	var m map[string]any
	if err := json.Unmarshal(data, &m); err != nil {
		t.Fatalf("cannot parse %s: %v", path, err)
	}
	return m
}

func assertMCPEntry(t *testing.T, mcpPath string) {
	t.Helper()
	m := readJSONFile(t, mcpPath)
	servers, ok := m["mcpServers"].(map[string]any)
	if !ok {
		t.Fatalf("%s missing mcpServers key", mcpPath)
	}
	mom, ok := servers["mom"].(map[string]any)
	if !ok {
		t.Fatalf("%s missing mcpServers.mom", mcpPath)
	}
	cmd, _ := mom["command"].(string)
	if cmd == "" {
		t.Errorf("%s mcpServers.mom.command must not be empty, got %v", mcpPath, mom["command"])
	}
}

func setupMinimalMom(t *testing.T, dir string, harnesses []string) {
	t.Helper()
	momDir := filepath.Join(dir, ".mom")
	for _, d := range []string{"memory", "constraints", "skills", "logs", "cache", "raw"} {
		os.MkdirAll(filepath.Join(momDir, d), 0755)
	}

	cfg := config.Default()
	cfg.Harnesses = make(map[string]config.HarnessConfig)
	for _, rt := range harnesses {
		cfg.Harnesses[rt] = config.HarnessConfig{Enabled: true}
	}
	cfg.Communication.Mode = "efficient"
	if err := config.Save(momDir, &cfg); err != nil {
		t.Fatalf("saving config: %v", err)
	}

	// Write minimal identity and schema so upgrade doesn't fail.
	os.WriteFile(filepath.Join(momDir, "identity.json"), []byte(`{"old": true}`), 0644)
	os.WriteFile(filepath.Join(momDir, "schema.json"), []byte(`{"old": true}`), 0644)
}

// ── Test 1: Init with all harnesses ──────────────────────────────────────────

func TestIntegration_InitAllHarnesses(t *testing.T) {
	dir := t.TempDir()
	home := t.TempDir()
	t.Setenv("HOME", home) // isolate global configs

	allHarnesses := []string{"claude", "codex", "windsurf", "pi"}
	initProject(t, dir, allHarnesses)

	// ── central .mom/ structure ──
	assertFileNotExists(t, filepath.Join(dir, ".mom"))
	assertFileExists(t, filepath.Join(home, ".mom", "config.yaml"))
	assertFileExists(t, filepath.Join(home, ".mom", "identity.json"))
	assertFileExists(t, filepath.Join(home, ".mom", "schema.json"))

	cfg, err := config.Load(filepath.Join(home, ".mom"))
	if err != nil {
		t.Fatalf("loading config: %v", err)
	}
	enabled := cfg.EnabledHarnesses()
	if len(enabled) != 4 {
		t.Errorf("expected 4 enabled harnesses, got %d: %v", len(enabled), enabled)
	}

	// ── Claude ──
	claudeMD := filepath.Join(home, ".claude", "CLAUDE.md")
	assertFileExists(t, claudeMD)
	assertFileContains(t, claudeMD, "Generated by MOM")

	settingsJSON := filepath.Join(home, ".claude", "settings.json")
	assertFileExists(t, settingsJSON)
	assertFileContains(t, settingsJSON, "mom watch --sweep")
	assertFileExists(t, filepath.Join(home, ".claude.json"))

	// ── Codex ──
	agentsMD := filepath.Join(home, ".codex", "AGENTS.md")
	assertFileExists(t, agentsMD)
	assertFileContains(t, agentsMD, "Generated by MOM")
	assertFileContains(t, filepath.Join(home, ".codex", "config.toml"), "mcp_servers.mom")

	// ── Windsurf ──
	windsurfMD := filepath.Join(home, ".codeium", "windsurf", "memories", "global_rules.md")
	assertFileExists(t, windsurfMD)
	assertFileContains(t, windsurfMD, "Generated by MOM")

	windsurfHooks := filepath.Join(home, ".codeium", "windsurf", "hooks.json")
	assertFileExists(t, windsurfHooks)
	assertFileContains(t, windsurfHooks, "mom watch --sweep")

	// ── Pi ──
	piAgents := filepath.Join(home, ".pi", "agent", "AGENTS.md")
	assertFileExists(t, piAgents)
	assertFileContains(t, piAgents, "Generated by MOM")
	piExt := filepath.Join(home, ".pi", "agent", "extensions", "mom-tools.ts")
	assertFileExists(t, piExt)
	assertFileContains(t, piExt, "export default")
	assertFileContains(t, piExt, "pi.registerTool")

	// ── MCP config ──
	assertMCPEntry(t, filepath.Join(home, ".codeium", "windsurf", "mcp_config.json"))
	assertFileNotExists(t, filepath.Join(dir, ".mcp.json"))
}

// ── Test 2: Upgrade registers ALL harnesses (regression) ─────────────────────

func TestIntegration_UpgradeRegistersAllHarnesses(t *testing.T) {
	dir := t.TempDir()
	t.Setenv("HOME", dir)

	allHarnesses := []string{"claude", "codex", "windsurf", "pi"}
	setupMinimalMom(t, dir, allHarnesses)

	// No harness artifacts exist yet — this simulates the bug scenario.
	assertFileNotExists(t, filepath.Join(dir, ".claude", "CLAUDE.md"))
	assertFileNotExists(t, filepath.Join(dir, "AGENTS.md"))
	assertFileNotExists(t, filepath.Join(dir, ".windsurf", "rules", "mom.md"))
	assertFileNotExists(t, filepath.Join(dir, ".pi", "extensions", "mom-tools.ts"))

	output := upgradeProject(t, dir)

	// ALL harnesses must be regenerated — not just Claude.
	for _, rt := range allHarnesses {
		if !strings.Contains(output, "harness "+rt+" context file regenerated") {
			t.Errorf("upgrade output missing regeneration for harness %s", rt)
		}
	}

	// ── Verify artifacts created for ALL harnesses ──
	assertFileExists(t, filepath.Join(dir, ".claude", "CLAUDE.md"))
	assertFileContains(t, filepath.Join(dir, ".claude", "CLAUDE.md"), "Generated by MOM")

	assertFileExists(t, filepath.Join(dir, ".claude", "settings.json"))
	assertFileContains(t, filepath.Join(dir, ".claude", "settings.json"), "mom watch --sweep")

	assertFileExists(t, filepath.Join(dir, "AGENTS.md"))
	assertFileExists(t, filepath.Join(dir, ".codex", "hooks.json"))
	assertFileContains(t, filepath.Join(dir, ".codex", "hooks.json"), "mom watch --sweep")

	assertFileExists(t, filepath.Join(dir, ".windsurf", "rules", "mom.md"))
	assertFileExists(t, filepath.Join(dir, ".windsurf", "hooks.json"))
	assertFileContains(t, filepath.Join(dir, ".windsurf", "hooks.json"), "working_directory")

	// Pi: extension must be deployed by upgrade too.
	assertFileExists(t, filepath.Join(dir, ".pi", "extensions", "mom-tools.ts"))
	assertFileContains(t, filepath.Join(dir, ".pi", "extensions", "mom-tools.ts"), "pi.registerTool")

	// MCP config must exist with mom entry.
	assertMCPEntry(t, filepath.Join(dir, ".mcp.json"))
}

// ── Test 3: Upgrade is local to the current filesystem project ─────────────

func TestIntegration_UpgradeDoesNotPropagateScopes(t *testing.T) {
	root := t.TempDir()
	t.Setenv("HOME", root)

	// Build hierarchy: root (user) → org-a (org) → repo-1, repo-2 (repos)
	orgDir := filepath.Join(root, "org-a")
	repo1 := filepath.Join(orgDir, "repo-1")
	repo2 := filepath.Join(orgDir, "repo-2")

	for _, d := range []string{repo1, repo2} {
		os.MkdirAll(filepath.Join(d, ".git"), 0755)
	}

	// Init .mom/ at each level with claude only.
	for _, pair := range []struct {
		dir   string
		scope string
	}{
		{root, "user"},
		{orgDir, "org"},
		{repo1, "repo"},
		{repo2, "repo"},
	} {
		momDir := filepath.Join(pair.dir, ".mom")
		os.MkdirAll(filepath.Join(momDir, "memory"), 0755)
		cfg := config.Default()
		cfg.Scope = pair.scope
		config.Save(momDir, &cfg)
		os.WriteFile(filepath.Join(momDir, "identity.json"), []byte(`{"old": true}`), 0644)
		os.WriteFile(filepath.Join(momDir, "schema.json"), []byte(`{"old": true}`), 0644)
	}

	upgradeProject(t, root)

	rootSchema, err := os.ReadFile(filepath.Join(root, ".mom", "schema.json"))
	if err != nil {
		t.Fatalf("missing root schema.json: %v", err)
	}
	if string(rootSchema) == `{"old": true}` {
		t.Fatal("root schema.json was not updated")
	}
	assertFileExists(t, filepath.Join(root, ".claude", "CLAUDE.md"))

	for _, d := range []string{orgDir, repo1, repo2} {
		schemaPath := filepath.Join(d, ".mom", "schema.json")
		data, err := os.ReadFile(schemaPath)
		if err != nil {
			t.Errorf("missing schema.json in %s", d)
			continue
		}
		if string(data) != `{"old": true}` {
			t.Errorf("schema.json unexpectedly updated in %s", d)
		}
	}
}

// ── Test 4: Add harnesses via upgrade ────────────────────────────────────────

func TestIntegration_AddHarnessesViaUpgrade(t *testing.T) {
	dir := t.TempDir()
	t.Setenv("HOME", dir)

	// Set up a minimal .mom/ with claude only (avoids cobra flag leakage).
	setupMinimalMom(t, dir, []string{"claude"})

	// Claude artifacts do NOT exist yet (setupMinimalMom only creates config).
	assertFileNotExists(t, filepath.Join(dir, ".windsurf", "rules", "mom.md"))
	assertFileNotExists(t, filepath.Join(dir, "AGENTS.md"))

	// Run upgrade to generate claude artifacts.
	upgradeProject(t, dir)

	// Claude artifacts should exist now.
	assertFileExists(t, filepath.Join(dir, ".claude", "CLAUDE.md"))
	// Windsurf and Codex should NOT exist (only claude is in config).
	assertFileNotExists(t, filepath.Join(dir, ".windsurf", "rules", "mom.md"))
	assertFileNotExists(t, filepath.Join(dir, "AGENTS.md"))

	// Add windsurf + codex to config.
	momDir := filepath.Join(dir, ".mom")
	cfg, _ := config.Load(momDir)
	cfg.Harnesses["windsurf"] = config.HarnessConfig{Enabled: true}
	cfg.Harnesses["codex"] = config.HarnessConfig{Enabled: true}
	config.Save(momDir, cfg)

	// Upgrade should pick up new harnesses.
	upgradeProject(t, dir)

	// All three should now exist.
	assertFileExists(t, filepath.Join(dir, ".claude", "CLAUDE.md"))
	assertFileExists(t, filepath.Join(dir, ".windsurf", "rules", "mom.md"))
	assertFileExists(t, filepath.Join(dir, ".windsurf", "hooks.json"))
	assertFileExists(t, filepath.Join(dir, "AGENTS.md"))
	assertFileExists(t, filepath.Join(dir, ".codex", "hooks.json"))
	assertMCPEntry(t, filepath.Join(dir, ".mcp.json"))
}

// Test 5 (Record + Draft pipeline) was retired in #240 PR 3. The
// `mom draft` CLI command and its batch-processor surface are gone;
// drafting now happens via the watcher → bus → drafter clustering
// pipeline, which is integration-tested in cli/internal/drafter.

// ── Test 6: MCP config correctness ──────────────────────────────────────────

func TestIntegration_MCPConfigCorrectness(t *testing.T) {
	dir := t.TempDir()
	home := t.TempDir()
	t.Setenv("HOME", home)

	allHarnesses := []string{"claude", "codex", "windsurf"}
	initProject(t, dir, allHarnesses)

	mcpPath := filepath.Join(home, ".codeium", "windsurf", "mcp_config.json")

	// Verify structure.
	m := readJSONFile(t, mcpPath)
	servers, ok := m["mcpServers"].(map[string]any)
	if !ok {
		t.Fatal(".mcp.json missing mcpServers")
	}

	mom, ok := servers["mom"].(map[string]any)
	if !ok {
		t.Fatal(".mcp.json missing mcpServers.mom")
	}

	cmd, _ := mom["command"].(string)
	if cmd == "" {
		t.Errorf("mcpServers.mom.command must not be empty, got %v", mom["command"])
	}

	args, ok := mom["args"].([]any)
	if !ok || len(args) < 2 {
		t.Errorf("mcpServers.mom.args missing or too short: %v", mom["args"])
	}

	if _, ok := mom["env"]; ok {
		t.Error("global mcpServers.mom should not include project-specific env")
	}
}

// ── Test 7: Upgrade preserves custom MCP entries ────────────────────────────

func TestIntegration_UpgradePreservesCustomMCP(t *testing.T) {
	dir := t.TempDir()
	home := t.TempDir()
	t.Setenv("HOME", home)

	initProject(t, dir, []string{"claude", "windsurf"})

	mcpPath := filepath.Join(home, ".codeium", "windsurf", "mcp_config.json")

	// Add a custom MCP server entry alongside mom.
	m := readJSONFile(t, mcpPath)
	servers := m["mcpServers"].(map[string]any)
	servers["my-custom-server"] = map[string]any{
		"command": "my-server",
		"args":    []any{"start"},
	}
	m["mcpServers"] = servers

	data, _ := json.MarshalIndent(m, "", "  ")
	data = append(data, '\n')
	os.WriteFile(mcpPath, data, 0644)

	// Verify custom entry exists before upgrade.
	pre := readJSONFile(t, mcpPath)
	preSrv := pre["mcpServers"].(map[string]any)
	if _, ok := preSrv["my-custom-server"]; !ok {
		t.Fatal("custom server not written to .mcp.json")
	}

	// Re-run init.
	initProject(t, dir, []string{"claude", "windsurf"})

	// Verify both mom and custom server survive.
	post := readJSONFile(t, mcpPath)
	postSrv := post["mcpServers"].(map[string]any)

	if _, ok := postSrv["mom"]; !ok {
		t.Error("mcpServers.mom missing after upgrade")
	}
	if _, ok := postSrv["my-custom-server"]; !ok {
		t.Error("mcpServers.my-custom-server lost after upgrade — custom entries not preserved")
	}

	// Verify custom server content is intact.
	custom := postSrv["my-custom-server"].(map[string]any)
	if custom["command"] != "my-server" {
		t.Errorf("custom server command = %v, want my-server", custom["command"])
	}
}
